///|
pub extend Limits with Eq::{equal, not_equal}

///|
pub extend Limits with ToJson::{to_json}

///|
pub extend Diagnostic with Eq::{equal, not_equal}

///|
pub extend Diagnostic with ToJson::{to_json}

///|
pub extend Options with Eq::{equal, not_equal}

///|
pub extend Options with ToJson::{to_json}

///|
pub extend FieldValue with Eq::{equal, not_equal}

///|
pub extend FieldValue with ToJson::{to_json}

///|
pub extend RowData with Eq::{equal, not_equal}

///|
pub extend RowData with ToJson::{to_json}

///|
pub extend CellChange with Eq::{equal, not_equal}

///|
pub extend CellChange with ToJson::{to_json}

///|
pub extend RowChange with Eq::{equal, not_equal}

///|
pub extend RowChange with ToJson::{to_json}

///|
pub extend Summary with Eq::{equal, not_equal}

///|
pub extend Summary with ToJson::{to_json}

///|
pub extend DiffResult with Eq::{equal, not_equal}

///|
pub extend DiffResult with ToJson::{to_json}
